// <auto-generated />
using System;
using InventoryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryApp.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260209121404_AddUnitPrice")]
    partial class AddUnitPrice
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryApp.Data.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("751c40cd-3b32-499c-8135-5c673c7be41a"),
                            IsDeleted = false,
                            Price = 2500m,
                            Quantity = 5,
                            Supplier = "BMW",
                            Title = "Engine for BMW 3-series 3.0 Diesel",
                            UnitPrice = 500m
                        },
                        new
                        {
                            Id = new Guid("d8bc1d18-5b35-4d6f-a194-5055b7a55591"),
                            IsDeleted = false,
                            Price = 3200m,
                            Quantity = 3,
                            Supplier = "BMW",
                            Title = "Engine for BMW 5-series 2.0 Diesel",
                            UnitPrice = 1066.67m
                        },
                        new
                        {
                            Id = new Guid("4969bcf2-9067-4662-ac5e-07a77a14abe9"),
                            IsDeleted = false,
                            Price = 4100m,
                            Quantity = 2,
                            Supplier = "Audi",
                            Title = "Automatic Gearbox for Audi A4 B8",
                            UnitPrice = 2050m
                        },
                        new
                        {
                            Id = new Guid("a6b3ac66-4b56-4ac0-a514-270291e6a6f9"),
                            IsDeleted = false,
                            Price = 1200m,
                            Quantity = 6,
                            Supplier = "Volkswagen",
                            Title = "Turbocharger for VW Golf 7 2.0 TDI",
                            UnitPrice = 200m
                        },
                        new
                        {
                            Id = new Guid("3112a173-bd44-4b81-b1b0-56ad79d80462"),
                            IsDeleted = false,
                            Price = 850m,
                            Quantity = 10,
                            Supplier = "Mercedes-Benz",
                            Title = "Brake Kit for Mercedes C-Class W205",
                            UnitPrice = 85m
                        },
                        new
                        {
                            Id = new Guid("b513bdd4-8762-4fec-ac1c-d6b1e103e7b6"),
                            IsDeleted = false,
                            Price = 650m,
                            Quantity = 7,
                            Supplier = "Opel",
                            Title = "Clutch Set for Opel Insignia 2.0 CDTI",
                            UnitPrice = 92.86m
                        },
                        new
                        {
                            Id = new Guid("3dd2bb17-c0be-4763-92d2-3b0bfa275b41"),
                            IsDeleted = false,
                            Price = 1800m,
                            Quantity = 4,
                            Supplier = "BMW",
                            Title = "Suspension Kit for BMW X5 E70",
                            UnitPrice = 450m
                        },
                        new
                        {
                            Id = new Guid("cc55c101-70d4-4698-a432-0b59e9613b4c"),
                            IsDeleted = false,
                            Price = 420m,
                            Quantity = 8,
                            Supplier = "BMW",
                            Title = "Fuel Injector for BMW 320d E90",
                            UnitPrice = 52.50m
                        },
                        new
                        {
                            Id = new Guid("9644ea59-0c94-4552-98f2-5557a9e24f15"),
                            IsDeleted = false,
                            Price = 780m,
                            Quantity = 5,
                            Supplier = "Audi",
                            Title = "Radiator for Audi A6 C7",
                            UnitPrice = 156m
                        },
                        new
                        {
                            Id = new Guid("3fd17b03-5233-4e6f-a799-34f9ec7a17cb"),
                            IsDeleted = false,
                            Price = 650m,
                            Quantity = 4,
                            Supplier = "Mercedes-Benz",
                            Title = "Alternator for Mercedes E-Class W212",
                            UnitPrice = 162.50m
                        },
                        new
                        {
                            Id = new Guid("f724ed54-7ec3-4b84-ad48-ec75ceb90c98"),
                            IsDeleted = false,
                            Price = 390m,
                            Quantity = 6,
                            Supplier = "Volkswagen",
                            Title = "Starter Motor for VW Passat B7",
                            UnitPrice = 65m
                        },
                        new
                        {
                            Id = new Guid("1a890e5d-6e8e-4dae-af1f-474c76c9d008"),
                            IsDeleted = false,
                            Price = 1100m,
                            Quantity = 3,
                            Supplier = "BMW",
                            Title = "Timing Chain Kit for BMW N47 Engine",
                            UnitPrice = 366.67m
                        },
                        new
                        {
                            Id = new Guid("ee2d042d-7440-4261-8035-0fcc272a7092"),
                            IsDeleted = false,
                            Price = 2200m,
                            Quantity = 2,
                            Supplier = "Audi",
                            Title = "Air Suspension Compressor for Audi Q7",
                            UnitPrice = 1100m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
