// <auto-generated />
using System;
using InventoryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryApp.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    [Migration("20260209074614_SoftDelete")]
    partial class SoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryApp.Data.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6831fa9c-83c6-4abd-89e5-106c4b09438f"),
                            IsDeleted = false,
                            Price = 2500m,
                            Quantity = 5,
                            Supplier = "BMW",
                            Title = "Engine for BMW 3-series 3.0 Diesel"
                        },
                        new
                        {
                            Id = new Guid("17bc9ec4-ab00-489b-8435-0cb960ffa9c6"),
                            IsDeleted = false,
                            Price = 3200m,
                            Quantity = 3,
                            Supplier = "BMW",
                            Title = "Engine for BMW 5-series 2.0 Diesel"
                        },
                        new
                        {
                            Id = new Guid("1ff31e1a-6f46-461c-a05a-34634e79c9b7"),
                            IsDeleted = false,
                            Price = 4100m,
                            Quantity = 2,
                            Supplier = "Audi",
                            Title = "Automatic Gearbox for Audi A4 B8"
                        },
                        new
                        {
                            Id = new Guid("64cfe0b7-d90c-4009-9b49-9037fe85c852"),
                            IsDeleted = false,
                            Price = 1200m,
                            Quantity = 6,
                            Supplier = "Volkswagen",
                            Title = "Turbocharger for VW Golf 7 2.0 TDI"
                        },
                        new
                        {
                            Id = new Guid("48359c3f-59d3-4388-b41c-aacba5b95737"),
                            IsDeleted = false,
                            Price = 850m,
                            Quantity = 10,
                            Supplier = "Mercedes-Benz",
                            Title = "Brake Kit for Mercedes C-Class W205"
                        },
                        new
                        {
                            Id = new Guid("d6110ad1-22e3-4e1e-aab2-b80ea319f42a"),
                            IsDeleted = false,
                            Price = 650m,
                            Quantity = 7,
                            Supplier = "Opel",
                            Title = "Clutch Set for Opel Insignia 2.0 CDTI"
                        },
                        new
                        {
                            Id = new Guid("4f89b342-bc55-4c83-aa0c-02826eefb571"),
                            IsDeleted = false,
                            Price = 1800m,
                            Quantity = 4,
                            Supplier = "BMW",
                            Title = "Suspension Kit for BMW X5 E70"
                        },
                        new
                        {
                            Id = new Guid("2cde4658-859c-42ff-8ccc-656a54976435"),
                            IsDeleted = false,
                            Price = 420m,
                            Quantity = 8,
                            Supplier = "BMW",
                            Title = "Fuel Injector for BMW 320d E90"
                        },
                        new
                        {
                            Id = new Guid("6e64189b-fe0d-477b-b67d-7cfba2b4e2aa"),
                            IsDeleted = false,
                            Price = 780m,
                            Quantity = 5,
                            Supplier = "Audi",
                            Title = "Radiator for Audi A6 C7"
                        },
                        new
                        {
                            Id = new Guid("437be437-7e1f-46e0-832d-f8458e4a4363"),
                            IsDeleted = false,
                            Price = 650m,
                            Quantity = 4,
                            Supplier = "Mercedes-Benz",
                            Title = "Alternator for Mercedes E-Class W212"
                        },
                        new
                        {
                            Id = new Guid("94f559e8-1b05-4165-a0c8-7d9c3342b293"),
                            IsDeleted = false,
                            Price = 390m,
                            Quantity = 6,
                            Supplier = "Volkswagen",
                            Title = "Starter Motor for VW Passat B7"
                        },
                        new
                        {
                            Id = new Guid("13c2ade7-5831-45f0-a688-6be9b6c61138"),
                            IsDeleted = false,
                            Price = 1100m,
                            Quantity = 3,
                            Supplier = "BMW",
                            Title = "Timing Chain Kit for BMW N47 Engine"
                        },
                        new
                        {
                            Id = new Guid("8aed8b9c-7aab-4009-a94f-ce48d24faf3c"),
                            IsDeleted = false,
                            Price = 2200m,
                            Quantity = 2,
                            Supplier = "Audi",
                            Title = "Air Suspension Compressor for Audi Q7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
