// <auto-generated />
using System;
using InventoryApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryApp.Data.Migrations
{
    [DbContext(typeof(InventoryDbContext))]
    partial class InventoryDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InventoryApp.Data.Models.Inventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Supplier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Inventories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("085978eb-05e1-4be3-9384-aa14212a6037"),
                            Price = 2500m,
                            Quantity = 5,
                            Supplier = "BMW",
                            Title = "Engine for BMW 3-series 3.0 Diesel"
                        },
                        new
                        {
                            Id = new Guid("4ba3c86b-9c5b-40e6-8428-b1acbca3bd85"),
                            Price = 3200m,
                            Quantity = 3,
                            Supplier = "BMW",
                            Title = "Engine for BMW 5-series 2.0 Diesel"
                        },
                        new
                        {
                            Id = new Guid("0e7437a3-8948-421f-b459-db177f330793"),
                            Price = 4100m,
                            Quantity = 2,
                            Supplier = "Audi",
                            Title = "Automatic Gearbox for Audi A4 B8"
                        },
                        new
                        {
                            Id = new Guid("d48c9eca-6dd6-45dd-adb3-068228ffbd55"),
                            Price = 1200m,
                            Quantity = 6,
                            Supplier = "Volkswagen",
                            Title = "Turbocharger for VW Golf 7 2.0 TDI"
                        },
                        new
                        {
                            Id = new Guid("c4dcd3b6-51a3-4a9a-b34a-507e12f684c8"),
                            Price = 850m,
                            Quantity = 10,
                            Supplier = "Mercedes-Benz",
                            Title = "Brake Kit for Mercedes C-Class W205"
                        },
                        new
                        {
                            Id = new Guid("9e3b5667-6da5-456e-ba60-b24f41ad6fa0"),
                            Price = 650m,
                            Quantity = 7,
                            Supplier = "Opel",
                            Title = "Clutch Set for Opel Insignia 2.0 CDTI"
                        },
                        new
                        {
                            Id = new Guid("9b68ede3-19c6-4954-81b6-bdf0695b2a88"),
                            Price = 1800m,
                            Quantity = 4,
                            Supplier = "BMW",
                            Title = "Suspension Kit for BMW X5 E70"
                        },
                        new
                        {
                            Id = new Guid("59dde9db-8a8e-4cbd-858b-6c29d130990e"),
                            Price = 420m,
                            Quantity = 8,
                            Supplier = "BMW",
                            Title = "Fuel Injector for BMW 320d E90"
                        },
                        new
                        {
                            Id = new Guid("f2607650-2282-4f91-bfdb-88c915567aad"),
                            Price = 780m,
                            Quantity = 5,
                            Supplier = "Audi",
                            Title = "Radiator for Audi A6 C7"
                        },
                        new
                        {
                            Id = new Guid("65c5da32-4822-4ed8-9958-d5770f5604bc"),
                            Price = 650m,
                            Quantity = 4,
                            Supplier = "Mercedes-Benz",
                            Title = "Alternator for Mercedes E-Class W212"
                        },
                        new
                        {
                            Id = new Guid("20ccf995-0033-4135-a071-0ed9aa0db956"),
                            Price = 390m,
                            Quantity = 6,
                            Supplier = "Volkswagen",
                            Title = "Starter Motor for VW Passat B7"
                        },
                        new
                        {
                            Id = new Guid("99ff52ab-71f5-420b-b8c0-e52e55c4e8e3"),
                            Price = 1100m,
                            Quantity = 3,
                            Supplier = "BMW",
                            Title = "Timing Chain Kit for BMW N47 Engine"
                        },
                        new
                        {
                            Id = new Guid("d2a5ec85-cfac-4d20-8714-55fb69b105dc"),
                            Price = 2200m,
                            Quantity = 2,
                            Supplier = "Audi",
                            Title = "Air Suspension Compressor for Audi Q7"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
